### ISSUE TITLE
Exception: No files for split=[train] found in /workshop/user_data/hgh/data/cityspaces\leftImg8bit\train

### ISSUE THREAD

**Issue by JasonmorrowGuo** [Andy-zhujunwen/pytorch-CBAM-Segmentation-experiment-#1]
Hello!This error occurred when I ran your code on Windows with Python 3:Exception: No files for split=[train] found in /workshop/user_data/hgh/data/cityspaces\leftImg8bit\train.Maybe I put cityscapes dataset in the wrong folder.Could you tell me where did you put cityscapes dataset?

**Comment by Andy-zhujunwen** [comment]
/workshop/user_data/hgh/data/cityspaces is the datasets directory path,you should change the path that your dataset in.
